###
### Default configuration
###

version: "3.3"

services:
  container:
    image: ${DOCKER_IMAGE}
    # Listen on TCP port 7 (Echo Protocol) and mirror input to output
    command: /usr/bin/ncat -l 7 -k -c /bin/cat
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
    expose:
      - 7/tcp
    networks:
      default:
        aliases:
          - container.local

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - container
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=container.local:7
      - WAIT_FOR_TIMEOUT=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - container
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=container.local:7
      - WAIT_FOR_TIMEOUT=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  test_project_dir:
